format:
  html:
    citations-hover: true
    css: "res/default.css"
    from: markdown+hard_line_breaks
    link-external-icon: true

date-format: iso

project:
  type: website
  output-dir: test
  render: ["*", "!docs", "!test"]

deploy:
  post-render: "sh encrypt.sh"

title-prefix: ""

website:
  comments:
    hypothesis:
      openSidebar: false
      showHighlights: whenSidebarOpen
      theme: clean
  favicon: "res/favicon/favicon.ico"
  open-graph:
    locale: en_US
  repo-url: "https://github.com/JJJHolscher/jjjholscher.github.io"
  repo-branch: "gh-pages"
  search: true
  site-url: "https://www.mousetrap.blog"
  title: "MouseTrap"
  twitter-card:
    creator: "@joowpie"
    site: "@joowpie"
